spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/by1902
      initial-size: 5
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.by.model


server:
  port: 8081

# 配置pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count
